@echo off
set "CONDA_BACKUP_GOOS=%GOOS%"
set "GOOS=@GOOS@"

set "CONDA_BACKUP_GOARCH=%GOARCH%"
set "GOARCH=@GOARCH@"

if "%CONDA_BUILD%"==1 (
  set "CONDA_BACKUP_GOPATH=%GOPATH%"
  set "GOPATH=%SRC_DIR%"

  set "CONDA_BACKUP_GO_PATH=%PATH%"
  set "PATH=%GOPATH%\bin;%PATH%"
)
