@echo off
if "%CONDA_BUILD%"==1 (
  set "GOPATH=%CONDA_BACKUP_GOPATH%"
  set "CONDA_BACKUP_GOPATH="

  set "PATH=%CONDA_BACKUP_GO_PATH%"
  set "CONDA_BACKUP_GO_PATH="
)

set "GOOS=%CONDA_BACKUP_GOOS%"
set "CONDA_BACKUP_GOOS="

set "GOARCH=%CONDA_BACKUP_GOARCH%"
set "CONDA_BACKUP_GOARCH="
