{% set name = "go" %}
{% set version = "1.16.10" %}

package:
  name: {{ name }}-{{ go_variant_str }}
  version: {{ version }}

source:
  - folder: go
    url: https://dl.google.com/{{ name }}/go{{ version }}.src.tar.gz
    sha256: a905472011585e403d00d2a41de7ced29b8884309d73482a307f689fd0f320b5
    patches:
      # Please see patches/README.md for more details
      - patches/0001-issue10607-is-only-valid-when-running-with-CGO.patch
      - patches/0002-Fix-cgo_fortran-test-setup-for-conda.patch
      - patches/0003-Add-CC-C-CPP-LD-FLAGS-to-script_test-extraEnvKeys.patch
      - patches/0004-Inherit-CGO_-environment-variables.patch
      - patches/0005-Add-conda-aware-default-values-for-GOPATH-and-GOBIN.patch
      - patches/0006-cmd-link-internal-ld-disable-testWindowsBuildmodeCSh.patch
  - folder: go-bootstrap  # [aarch64 or ppc64le or osx]
    url: https://dl.google.com/go/go1.11.13.linux-arm64.tar.gz  # [aarch64]
    sha256: e94329c97b38b5bffe9c18e84e9f521dc995e02df7696897a7626293da9ac593  # [aarch64]
    url: https://dl.google.com/go/go1.11.13.linux-ppc64le.tar.gz  # [ppc64le]
    sha256: ad3c7397ddd41a5af9d9bf3c560d3d0f8c1bdef4ac4d21819a021ea88e25efca  # [ppc64le]
    url: https://storage.googleapis.com/golang/go1.16.darwin-arm64.tar.gz  # [osx and build_platform == "osx-arm64"]
    sha256: 4dac57c00168d30bbd02d95131d5de9ca88e04f2c5a29a404576f30ae9b54810  # [osx and build_platform == "osx-arm64"]
    url: https://storage.googleapis.com/golang/go1.16.darwin-amd64.tar.gz  # [osx and build_platform == "osx-64"]
    sha256: 6000a9522975d116bf76044967d7e69e04e982e9625330d9a539a8b45395f9a8  # [osx and build_platform == "osx-64"]

build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  force_ignore_keys:   # [win]
    - c_compiler        # [win]
    - cxx_compiler      # [win]
    - fortran_compiler  # [win]
  # test data links to these DSOs
  missing_dso_whitelist:
    - $RPATH/libc.so.6             # [linux and not cgo]
    - /usr/lib/libSystem.B.dylib   # [osx]
    - $SYSROOT\System32\winmm.dll  # [win]
  number: 1

requirements:
  run:
    - {{ pin_subpackage(name, exact=true) }}
    - {{ compiler('c') }}  # [unix and cgo]
    - {{ compiler('m2w64_c') }}  # [win and cgo]

test:
  commands:
    - go help

outputs:
  - name: {{ name }}
    script: {{ go_variant_str }}/build.sh  # [unix]
    script: {{ go_variant_str }}/build.bat  # [win]
    requirements:
      build:
        - {{ compiler('go14') }}  # [not (aarch64 or ppc64le or osx)]

        - {{ stdlib('c') }}        # [unix and cgo]
        - {{ compiler('c') }}        # [unix and cgo]
        - {{ compiler('cxx') }}      # [unix and cgo]
        - {{ compiler('fortran') }}  # [unix and cgo]

        - {{ stdlib('m2w64_c') }}        # [win and cgo]
        - {{ compiler('m2w64_c') }}        # [win and cgo]
        - {{ compiler('m2w64_cxx') }}      # [win and cgo]
        - {{ compiler('m2w64_fortran') }}  # [win and cgo]
      run:
        - _go_select =={{ go_variant_ver }}={{ go_variant_str }}
      run_constrained:
        # TODO: Move to run section once conda/conda#9845 is fixed
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx]

        - {{ pin_compatible(compiler('c')) }}        # [unix and cgo]
        - {{ pin_compatible(compiler('cxx')) }}      # [unix and cgo]
        - {{ pin_compatible(compiler('fortran')) }}  # [unix and cgo]

        - {{ pin_compatible(compiler('m2w64_c')) }}        # [win and cgo]
        - {{ pin_compatible(compiler('m2w64_cxx')) }}      # [win and cgo]
        - {{ pin_compatible(compiler('m2w64_fortran')) }}  # [win and cgo]
    test:
      requires:
        - {{ compiler('c') }}        # [unix and cgo]
        - {{ compiler('m2w64_c') }}  # [win and cgo]
        - git  # [linux]
        - perl
      script: {{ go_variant_str }}/test.sh  # [unix]
      script: {{ go_variant_str }}/test.bat  # [win]
    about:
      home: http://golang.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: go/LICENSE
      summary: The Go Programming Language

about:
  home: http://golang.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: go/LICENSE
  summary: The Go Programming Language ({{ go_variant_str }})
  description: |
    Go is expressive, concise, clean, and efficient. Its concurrency mechanisms
    make it easy to write programs that get the most out of multicore and
    networked machines, while its novel type system enables flexible and
    modular program construction. Go compiles quickly to machine code yet has
    the convenience of garbage collection and the power of run-time reflection.
    It's a fast, statically typed, compiled language that feels like a
    dynamically typed, interpreted language.
  doc_url: https://golang.org/doc
  dev_url: https://go.googlesource.com/go

extra:
  feedstock-name: go
  recipe-maintainers:
    - nehaljwani
    - scopatz
    - sodre
    - stuarteberg
    - xhochy
