{% set name = "go" %}
{% set version = "1.21.6" %}

package:
  name: {{ name }}-{{ go_variant_str }}
  version: {{ version }}

source:
  - folder: go
    url: https://dl.google.com/{{ name }}/go{{ version }}.src.tar.gz
    sha256: 124926a62e45f78daabbaedb9c011d97633186a33c238ffc1e25320c02046248
    patches:
      # Please see patches/README.md for more details
      - patches/0001-Fix-cgo_fortran-test-setup-for-conda.patch
      - patches/0002-Add-CC-C-CPP-LD-FLAGS-to-script_test-extraEnvKeys.patch
      - patches/0003-Inherit-CGO_-environment-variables.patch
      - patches/0004-Add-conda-aware-default-values-for-GOPATH-and-GOBIN.patch
      - patches/0005-cmd-link-internal-ld-disable-testWindowsBuildmodeCSh.patch
      - patches/0006-issue10607-is-only-valid-when-running-with-CGO.patch
      - patches/0007-Revert-cmd-link-enable-internal-linker-in-more-cases.patch
      - patches/0008-Mark-ftree-as-a-safe-compiler-flag.patch
  # Update this with a release from https://go.dev/dl/
  - folder: go-bootstrap  # [aarch64 or ppc64le or osx or win64 or (linux and x86_64)]
    url: https://go.dev/dl/go{{ version }}.linux-arm64.tar.gz  # [aarch64]
    sha256: e2e8aa88e1b5170a0d495d7d9c766af2b2b6c6925a8f8956d834ad6b4cacbd9a  # [aarch64]

    url: https://go.dev/dl/go{{ version }}.linux-amd64.tar.gz  # [linux and x86_64]
    sha256: 3f934f40ac360b9c01f616a9aa1796d227d8b0328bf64cb045c7b8c4ee9caea4  # [linux and x86_64]

    url: https://go.dev/dl/go{{ version }}.linux-ppc64le.tar.gz  # [ppc64le]
    sha256: e872b1e9a3f2f08fd4554615a32ca9123a4ba877ab6d19d36abc3424f86bc07f  # [ppc64le]

    url: https://go.dev/dl/go{{ version }}.windows-amd64.zip  # [win64]
    sha256: 27ac9dd6e66fb3fd0acfa6792ff053c86e7d2c055b022f4b5d53bfddec9e3301  # [win64]

    # url: https://go.dev/dl/go{{ version }}.darwin-arm64.tar.gz  # [osx and arm64]
    # sha256: 49e394ab92bc6fa3df3d27298ddf3e4491f99477bee9dd4934525a526f3a391c  # [osx and arm64]

    url: https://go.dev/dl/go{{ version }}.darwin-amd64.tar.gz  # [osx]
    sha256: 31d6ecca09010ab351e51343a5af81d678902061fee871f912bdd5ef4d778850  # [osx]

build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  force_ignore_keys:   # [win]
    - c_compiler        # [win]
    - cxx_compiler      # [win]
    - fortran_compiler  # [win]
  # test data links to these DSOs
  missing_dso_whitelist:
    - $RPATH/libc.so.6             # [linux and not cgo]
    - /usr/lib/libSystem.B.dylib   # [osx]
    - $SYSROOT\System32\winmm.dll  # [win]
  number: 0
  skip: true  # [linux and s390x]

requirements:
  run:
    - {{ pin_subpackage(name, exact=true) }}
    - {{ compiler('c') }}  # [unix and cgo]
    - {{ compiler('m2w64_c') }}  # [win and cgo]

test:
  commands:
    - go help

outputs:
  - name: {{ name }}
    script: {{ go_variant_str }}/build.sh  # [unix]
    script: {{ go_variant_str }}/build.bat  # [win]

    build:   # [linux64 and cgo]
      binary_relocation: false  # [linux64 and cgo]
      detect_binary_files_with_prefix: false  # [linux64 and cgo]
      run_exports:   # [linux64 and cgo]
        strong:   # [linux64 and cgo]
          - __glibc >=2.17                    # [linux64 and cgo]
    requirements:
      build:
        - {{ compiler('c') }}        # [unix and cgo]
        - sysroot_linux-64 2.17      # [linux64 and cgo]
        - {{ compiler('cxx') }}      # [unix and cgo]
        - {{ compiler('fortran') }}  # [unix and cgo]

        - {{ compiler('m2w64_c') }}        # [win and cgo]
        - {{ compiler('m2w64_cxx') }}      # [win and cgo]
        - {{ compiler('m2w64_fortran') }}  # [win and cgo]
      run:
        - _go_select =={{ go_variant_ver }}={{ go_variant_str }}
        - sysroot_linux-64 2.17      # [linux64 and cgo]
      run_constrained:
        # TODO: Move to run section once conda/conda#9845 is fixed
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx]

        - {{ pin_compatible(compiler('c')) }}        # [unix and cgo]
        - {{ pin_compatible(compiler('cxx')) }}      # [unix and cgo]
        - {{ pin_compatible(compiler('fortran')) }}  # [unix and cgo]

        - {{ pin_compatible(compiler('m2w64_c')) }}        # [win and cgo]
        - {{ pin_compatible(compiler('m2w64_cxx')) }}      # [win and cgo]
        - {{ pin_compatible(compiler('m2w64_fortran')) }}  # [win and cgo]
    test:
      requires:
        - {{ compiler('c') }}        # [unix and cgo]
        - {{ compiler('m2w64_c') }}  # [win and cgo]
        - git  # [linux]
        - perl
      files:
        - {{ go_variant_str }}
      commands:
        - chmod +x {{ go_variant_str }}/test.sh   # [unix]
        - ./{{ go_variant_str }}/test.sh   # [unix]
        - {{ go_variant_str }}/test.bat  # [win]
    about:
      home: https://go.dev/
      license: BSD-3-Clause
      license_family: BSD
      license_file: go/LICENSE
      summary: The Go Programming Language

about:
  home: https://go.dev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: go/LICENSE
  summary: The Go Programming Language ({{ go_variant_str }})
  description: |
    Go is expressive, concise, clean, and efficient. Its concurrency mechanisms
    make it easy to write programs that get the most out of multicore and
    networked machines, while its novel type system enables flexible and
    modular program construction. Go compiles quickly to machine code yet has
    the convenience of garbage collection and the power of run-time reflection.
    It's a fast, statically typed, compiled language that feels like a
    dynamically typed, interpreted language.
  doc_url: https://go.dev/doc
  dev_url: https://github.com/golang/

extra:
  feedstock-name: go
  recipe-maintainers:
    - nehaljwani
    - scopatz
    - sodre
    - stuarteberg
    - xhochy
    - hmaarrfk
