{% set name = "go" %}
{% set version = "1.18.5" %}

package:
  name: {{ name }}-{{ go_variant_str }}
  version: {{ version }}

source:
  - folder: go
    url: https://dl.google.com/{{ name }}/go{{ version }}.src.tar.gz
    sha256: 9920d3306a1ac536cdd2c796d6cb3c54bc559c226fc3cc39c32f1e0bd7f50d2a
    patches:
      # Please see patches/README.md for more details
      - patches/0001-Fix-cgo_fortran-test-setup-for-conda.patch
      - patches/0002-Add-CC-C-CPP-LD-FLAGS-to-script_test-extraEnvKeys.patch
      - patches/0003-Inherit-CGO_-environment-variables.patch
      - patches/0004-Add-conda-aware-default-values-for-GOPATH-and-GOBIN.patch
      - patches/0005-cmd-link-internal-ld-disable-testWindowsBuildmodeCSh.patch
      - patches/0006-issue10607-is-only-valid-when-running-with-CGO.patch
      # https://github.com/conda-forge/go-feedstock/pull/150#issuecomment-1153458502
      - patches/0007-Revert-cmd-link-enable-internal-linker-in-more-cases.patch
      # 0008 has been integrated into 1.19
      # https://github.com/golang/go/issues/53013
      - patches/0008-osx-clang14-2cfbef4.diff
      # See https://github.com/golang/go/issues/57044 and https://github.com/golang/go/issues/53000
      - patches/e6adccb3c56385f8d840165008f2606098e13e56.patch
      # See https://go-review.googlesource.com/c/go/+/490818
      - patches/a9a01ea.patch
      # https://go-review.googlesource.com/c/go/+/472295
      - patches/bb8f9a6.patch
  # Update this with a release from https://go.dev/dl/
  - folder: go-bootstrap  # [aarch64 or ppc64le or osx or win64]
    url: https://go.dev/dl/go{{ version }}.linux-arm64.tar.gz  # [aarch64]
    sha256: 006f6622718212363fa1ff004a6ab4d87bbbe772ec5631bab7cac10be346e4f1  # [aarch64]

    url: https://go.dev/dl/go{{ version }}.linux-ppc64le.tar.gz  # [ppc64le]
    sha256: 2e37fb9c7cbaedd4e729492d658aa4cde821fc94117391a8105c13b25ca1c84b  # [ppc64le]

    url: https://go.dev/dl/go{{ version }}.windows-amd64.zip  # [win64]
    sha256: 73753620602d4b4469770040c53db55e5dd6af2ad07ecc18f71f164c3224eaad  # [win64]

    url: https://go.dev/dl/go{{ version }}.darwin-arm64.tar.gz  # [osx and build_platform == "osx-arm64"]
    sha256: 923a377c6fc9a2c789f5db61c24b8f64133f7889056897449891f256af34065f  # [osx and build_platform == "osx-arm64"]

    url: https://go.dev/dl/go{{ version }}.darwin-amd64.tar.gz  # [osx and build_platform == "osx-64"]
    sha256: 828eeca8b5abea3e56921df8fa4b1101380a5ebcfee10acbc8ffe7ec0bf5876b  # [osx and build_platform == "osx-64"]

build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  force_ignore_keys:   # [win]
    - c_compiler        # [win]
    - cxx_compiler      # [win]
    - fortran_compiler  # [win]
  # test data links to these DSOs
  missing_dso_whitelist:
    - $RPATH/libc.so.6             # [linux and not cgo]
    - /usr/lib/libSystem.B.dylib   # [osx]
    - $SYSROOT\System32\winmm.dll  # [win]
  number: 3

requirements:
  run:
    - {{ pin_subpackage(name, exact=true) }}
    - {{ compiler('c') }}  # [unix and cgo]
    - {{ compiler('m2w64_c') }}  # [win and cgo]

test:
  commands:
    - go help

outputs:
  - name: {{ name }}
    script: {{ go_variant_str }}/build.sh  # [unix]
    script: {{ go_variant_str }}/build.bat  # [win]
    requirements:
      build:
        - {{ compiler('go14') }}  # [not (aarch64 or ppc64le or osx or win64)]

        - {{ compiler('c') }}        # [unix and cgo]
        - {{ compiler('cxx') }}      # [unix and cgo]
        - {{ compiler('fortran') }}  # [unix and cgo]

        - {{ compiler('m2w64_c') }}        # [win and cgo]
        - {{ compiler('m2w64_cxx') }}      # [win and cgo]
        - {{ compiler('m2w64_fortran') }}  # [win and cgo]
      run:
        - _go_select =={{ go_variant_ver }}={{ go_variant_str }}
      run_constrained:
        # TODO: Move to run section once conda/conda#9845 is fixed
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx]

        - {{ pin_compatible(compiler('c')) }}        # [unix and cgo]
        - {{ pin_compatible(compiler('cxx')) }}      # [unix and cgo]
        - {{ pin_compatible(compiler('fortran')) }}  # [unix and cgo]

        - {{ pin_compatible(compiler('m2w64_c')) }}        # [win and cgo]
        - {{ pin_compatible(compiler('m2w64_cxx')) }}      # [win and cgo]
        - {{ pin_compatible(compiler('m2w64_fortran')) }}  # [win and cgo]
    test:
      requires:
        - {{ compiler('c') }}        # [unix and cgo]
        - {{ compiler('m2w64_c') }}  # [win and cgo]
        - git  # [linux]
        - perl
      script: {{ go_variant_str }}/test.sh  # [unix]
      script: {{ go_variant_str }}/test.bat  # [win]
    about:
      home: http://golang.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: go/LICENSE
      summary: The Go Programming Language

about:
  home: http://golang.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: go/LICENSE
  summary: The Go Programming Language ({{ go_variant_str }})
  description: |
    Go is expressive, concise, clean, and efficient. Its concurrency mechanisms
    make it easy to write programs that get the most out of multicore and
    networked machines, while its novel type system enables flexible and
    modular program construction. Go compiles quickly to machine code yet has
    the convenience of garbage collection and the power of run-time reflection.
    It's a fast, statically typed, compiled language that feels like a
    dynamically typed, interpreted language.
  doc_url: https://golang.org/doc
  dev_url: https://go.googlesource.com/go

extra:
  feedstock-name: go
  recipe-maintainers:
    - nehaljwani
    - scopatz
    - sodre
    - stuarteberg
    - xhochy
    - hmaarrfk
