{% set name = "go" %}
{% set version = "1.25.1" %}

package:
  name: {{ name }}-{{ go_variant_str }}-split
  version: {{ version }}

source:
  - folder: go
    url: https://dl.google.com/{{ name }}/go{{ version }}.src.tar.gz
    sha256: d010c109cee94d80efe681eab46bdea491ac906bf46583c32e9f0dbb0bd1a594
    patches:
      # Please see patches/README.md for more details
      - patches/0001-Fix-cgo_fortran-test-setup-for-conda.patch
      - patches/0002-Add-CC-C-CPP-LD-FLAGS-to-script_test-extraEnvKeys.patch
      - patches/0003-Inherit-CGO_-environment-variables.patch
      - patches/0004-Add-conda-aware-default-values-for-GOPATH-and-GOBIN.patch
      - patches/0005-cmd-link-internal-ld-disable-testWindowsBuildmodeCSh.patch
      - patches/0006-Revert-cmd-link-enable-internal-linker-in-more-cases.patch
      - patches/0007-Mark-ftree-as-a-safe-compiler-flag.patch
  # Update this with a release from https://go.dev/dl/
  - folder: go-bootstrap
    url: https://go.dev/dl/go{{ version }}.linux-amd64.tar.gz  # [build_platform == "linux-64"]
    sha256: 7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e  # [build_platform == "linux-64"]

    url: https://go.dev/dl/go{{ version }}.windows-amd64.zip  # [win64]
    sha256: 4a974de310e7ee1d523d2fcedb114ba5fa75408c98eb3652023e55ccf3fa7cab  # [win64]

    # url: https://go.dev/dl/go{{ version }}.darwin-arm64.tar.gz  # [osx and arm64]
    # sha256: 49e394ab92bc6fa3df3d27298ddf3e4491f99477bee9dd4934525a526f3a391c  # [osx and arm64]

    url: https://go.dev/dl/go{{ version }}.darwin-amd64.tar.gz  # [osx]
    sha256: 1d622468f767a1b9fe1e1e67bd6ce6744d04e0c68712adc689748bbeccb126bb  # [osx]

build:
  number: 0
  skip: true  # [linux and s390x]

outputs:
  - name: go-{{ go_variant_str }}
    build:
      binary_relocation: false
      detect_binary_files_with_prefix: false
      force_ignore_keys:   # [win]
        - c_compiler        # [win]
        - cxx_compiler      # [win]
        - fortran_compiler  # [win]
      # test data links to these DSOs
      missing_dso_whitelist:
        - $RPATH/libc.so.6             # [linux and not cgo]
        - /usr/lib/libSystem.B.dylib   # [osx]
        - $SYSROOT\System32\winmm.dll  # [win]
    requirements:
      run:
        - {{ pin_subpackage(name, exact=true) }}
        - {{ compiler('c') }}  # [unix and cgo]
        - {{ compiler('m2w64_c') }}  # [win and cgo]
    test:
      commands:
        - go help

  - name: go
    script: {{ go_variant_str }}/build.sh  # [unix]
    script: {{ go_variant_str }}/build.bat  # [win]
    build:
      binary_relocation: false
      detect_binary_files_with_prefix: false
      run_exports:                            # [unix and cgo]
        strong:                               # [unix and cgo]
          - __glibc >={{ c_stdlib_version }}  # [linux and cgo]
          - __osx >=12                        # [osx and cgo]
    requirements:
      build:
        - {{ compiler('c') }}        # [unix and cgo]
        - {{ stdlib("c") }}          # [unix and cgo]
        - {{ compiler('cxx') }}      # [unix and cgo]
        - {{ compiler('fortran') }}  # [unix and cgo]

        - {{ compiler('m2w64_c') }}        # [win and cgo]
        - {{ stdlib("m2w64_c") }}          # [win and cgo]
        - {{ compiler('m2w64_cxx') }}      # [win and cgo]
        - {{ compiler('m2w64_fortran') }}  # [win and cgo]
      run:
        - _go_select =={{ go_variant_ver }}={{ go_variant_str }}
      run_constrained:
        # TODO: Move to run section once conda/conda#9845 is fixed

        - {{ pin_compatible(compiler('c')) }}        # [unix and cgo]
        - {{ pin_compatible(compiler('cxx')) }}      # [unix and cgo]
        - {{ pin_compatible(compiler('fortran')) }}  # [unix and cgo]

        - {{ pin_compatible(compiler('m2w64_c')) }}        # [win and cgo]
        - {{ pin_compatible(compiler('m2w64_cxx')) }}      # [win and cgo]
        - {{ pin_compatible(compiler('m2w64_fortran')) }}  # [win and cgo]
    test:
      requires:
        - {{ compiler('c') }}        # [unix and cgo]
        - {{ compiler('m2w64_c') }}  # [win and cgo]
        - git  # [unix]
        - perl
      files:
        - {{ go_variant_str }}
      commands:
        - chmod +x {{ go_variant_str }}/test.sh   # [unix]
        - ./{{ go_variant_str }}/test.sh   # [unix]
        - {{ go_variant_str }}/test.bat  # [win]
        - test "$GOTOOLCHAIN" = "local"   # [unix]
        - if not "%GOTOOLCHAIN%"=="local" exit /b 1  # [win]
    about:
      home: https://go.dev/
      license: BSD-3-Clause
      license_family: BSD
      license_file: go/LICENSE
      summary: The Go Programming Language

about:
  home: https://go.dev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: go/LICENSE
  summary: The Go Programming Language ({{ go_variant_str }})
  description: |
    Go is expressive, concise, clean, and efficient. Its concurrency mechanisms
    make it easy to write programs that get the most out of multicore and
    networked machines, while its novel type system enables flexible and
    modular program construction. Go compiles quickly to machine code yet has
    the convenience of garbage collection and the power of run-time reflection.
    It's a fast, statically typed, compiled language that feels like a
    dynamically typed, interpreted language.
  doc_url: https://go.dev/doc
  dev_url: https://github.com/golang/

extra:
  feedstock-name: go
  recipe-maintainers:
    - nehaljwani
    - scopatz
    - sodre
    - stuarteberg
    - xhochy
    - hmaarrfk
