bot:
  abi_migration_branches:
  - 1.15.x
  - 1.14.x
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
build_with_mambabuild: false
conda_forge_output_validation: true
test: native
conda_build:
  pkg_format: '2'
