bot:
  abi_migration_branches:
  - 1.17.x
  - 1.16.x
  - 1.15.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
build_with_mambabuild: false
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native
conda_build:
  pkg_format: '2'
