bot:
  abi_migration_branches:
  - 1.19.x
  - 1.18.x
  - 1.17.x
  - 1.16.x
  - 1.15.x
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native
conda_build:
  pkg_format: '2'
os_version:
  linux_64: cos7
