build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
test: native_and_emulated
