conda_forge_output_validation: true
build_platform: {osx_arm64: osx_64}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
bot:
  abi_migration_branches:
    - 1.15.x
    - 1.14.x
